DROP TABLE IF EXISTS currency CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS goods CASCADE;
DROP TABLE IF EXISTS owners CASCADE;
DROP TABLE IF EXISTS banking CASCADE;
DROP TABLE IF EXISTS ledger CASCADE;
DROP TABLE IF EXISTS credentials CASCADE;
